name: kdbx_example
description: Demonstrates how to use the kdbx plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  kdbx:
    path: ../

dev_dependencies:
  flutter_lints: ">=1.0.4 <2.0.0"
