name: kdbx_example
description: Demonstrates how to use the kdbx plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:

  kdbx:
    path: ../

dev_dependencies:
  pedantic: ^1.9.2
