name: kdbx
description: KeepassX format implementation in pure dart. (kdbx 3.x and 4.x support).
version: 1.0.0
homepage: https://github.com/authpass/kdbx.dart

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
#  flutter:
#    sdk: flutter
#  path: ^1.6.0
  logging: '>=0.11.3+2 <2.0.0'
  crypto: '>=2.0.0 <4.0.0'
  pointycastle: '>=1.0.1 <4.0.0'
  xml: '>=4.4.0 <6.0.0'
  uuid: ">=3.0.0 <5.0.0"
  meta: '>=1.0.0 <2.0.0'
  clock: '>=1.0.0 <2.0.0'
  convert: '>=2.0.0 <4.0.0'
  isolate: '>=2.0.3 <3.0.0'
  path: '>=1.6.0 <2.0.0'
  quiver: '>=2.1.0 <4.0.0'
  archive: '>=2.0.13 <4.0.0'
  supercharged_dart: '>=1.2.0 <4.0.0'
  synchronized: '>=2.2.0 <4.0.0'

  collection: '>=1.14.0 <2.0.0'

  # required for bin/
  args: '>1.5.0 <3.0.0'
  logging_appenders: '>=0.1.0 <2.0.0'
  argon2_ffi_base: ^1.0.0

dev_dependencies:
  pedantic: '>=1.7.0 <2.0.0'
  test: '>=1.6.0 <2.0.0'
  fake_async: ^1.1.0
